name: Automatic Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
          docker build -t pirullabot:2.0 .

    - name: Save Docker image to a tar file
      run: |
          docker save pirullabot:2.0 -o ~/pirullabot.tar

    - name: Create SSH Key
      run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ./pirullakey.pem
          chmod 0400 ./pirullakey.pem

    - name: Create .ssh directory
      run: |
          mkdir -p ~/.ssh

    - name: Add EC2 Host to Known Hosts
      run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy Docker image to EC2
      run: |
          scp -i ./pirullakey.pem ~/pirullabot.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

    - name: SSH and load Docker image on EC2
      run: |
          ssh -t -i ./pirullakey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          if ! systemctl is-active --quiet docker; then
            sudo systemctl start docker
          else
            echo 'docker running'
          fi
          sudo docker stop pirullabot || true
          sudo docker rm pirullabot || true
          # sudo docker system prune -a -f || true
          sudo docker load -i /home/${{ secrets.EC2_USER }}/pirullabot.tar
          sudo docker run -d -e YOUTUBE_DEVELOPER_KEY=${{ secrets.YOUTUBE_DEVELOPER_KEY }} -e CHANNEL_ID=${{ secrets.CHANNEL_ID }} -e TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} -e TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }} -e ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} -e ACCESS_SECRET_TOKEN=${{ secrets.ACCESS_SECRET_TOKEN }} -e BEARER_TOKEN=${{ secrets.BEARER_TOKEN }} -v /home/${{ secrets.EC2_USER }}/pirulla-bot/app/data:/app/data --name pirullabot pirullabot:2.0
          EOF
